'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Events', [
      {
        title: 'Играем в футбол',
        date: '2022-06-21 11:24:00+03',
        description: 'Собираемся на моей площадке, адрес приложен.',
        members_count: 10,
        user_id: 2,
        sport_id: 2,
        place_id: 8,
        cost: 0,
        phone: '89513878458',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Баскетбол на выходных',
        date: '2022-07-21 11:24:00+03',
        description: 'Ребята, очень всех жду.',
        members_count: 15,
        user_id: 9,
        sport_id: 1,
        place_id: 4,
        cost: 0,
        phone: 'Пишите в телеграм @yasport',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Снова собираемся на футбол',
        date: '2022-06-05 12:30:00+03',
        description: ' ',
        members_count: 12,
        user_id: 2,
        sport_id: 2,
        place_id: 5,
        cost: 0,
        phone: '+79966948596',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Настольный тенис',
        date: '2022-06-27 15:00:00+03',
        description: 'Небольшая плата, будем играть в настольный тенис + пикник',
        members_count: 10,
        user_id: 8,
        sport_id: 1,
        place_id: 2,
        cost: 100,
        phone: '89113845969',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Волейбол',
        date: '2022-07-02 09:00:00+03',
        description: 'красивая',
        members_count: 8,
        user_id: 4,
        sport_id: 8,
        place_id: 3,
        cost: 0,
        phone: '89113845969 whatsAp',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Баскетбол на фрунзенской',
        date: '2022-06-10 11:24:00+03',
        description: 'играем в баскетбол, пишите',
        members_count: 10,
        user_id: 6,
        sport_id: 1,
        place_id: 2,
        cost: 0,
        phone: '+79115845769',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'волейбол',
        date: '2022-06-21 12:00:00+03',
        description: ' ',
        members_count: 8,
        user_id: 3,
        sport_id: 8,
        place_id: 10,
        cost: 0,
        phone: 'телега: @noName',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Бадминтон',
        date: '2022-06-29 14:00:00+03',
        description: ' ',
        members_count: 10,
        user_id: 10,
        sport_id: 18,
        place_id: 13,
        cost: 0,
        phone: '89113845969',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Играем в шахматы',
        date: '2022-07-21 17:00:00+03',
        description: 'Турнир по шахматам. Начинаем вечером.',
        members_count: 10,
        user_id: 5,
        sport_id: 5,
        place_id: 7,
        cost: 200,
        phone: '89113847869 WA, Telegram',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'футбол',
        date: '2022-07-15 18:00:00+03',
        description: 'Звоните по номеру.',
        members_count: 10,
        user_id: 9,
        sport_id: 2,
        place_id: 15,
        cost: 0,
        phone: '89113845969',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'чемпионат по армрестлингу',
        date: '2022-07-08 13:30:00+03',
        description: 'Пока что я чемпион. Надеюсь найду достойного соперника.',
        members_count: 10,
        user_id: 5,
        sport_id: 6,
        place_id: 15,
        cost: 0,
        phone: 'тг: @lexa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Борьба',
        date: '2022-07-17 19:30:00+03',
        description: 'Поборемся?!',
        members_count: 10,
        user_id: 7,
        sport_id: 7,
        place_id: 13,
        cost: 0,
        phone: '89841528834',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Баскетбольное мироприятие',
        date: '2022-07-08 11:30:00+03',
        description: 'Набираю команду для игры в баскетбол, будет здорово. Хочу собираться пару раз в месяц.',
        members_count: 14,
        user_id: 6,
        sport_id: 1,
        place_id: 9,
        cost: 0,
        phone: 'WA: 89113845969',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Регби сбор',
        date: '2022-06-05 12:30:00+03',
        description: 'Не хватает 5 человек для игры в регби.',
        members_count: 5,
        user_id: 9,
        sport_id: 16,
        place_id: 15,
        cost: 0,
        phone: '89148575839',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Велосипедная прогулка',
        date: '2022-06-06 11:30:00+03',
        description: ' Собираем велосипедгную пргогулку. Начальная точка у площадки.',
        members_count: 10,
        user_id: 4,
        sport_id: 13,
        place_id: 9,
        cost: 0,
        phone: 'телеграм: 89113845969',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Баскетбол',
        date: '2022-06-28 10:30:00+03',
        description: ' ',
        members_count: 16,
        user_id: 3,
        sport_id: 1,
        place_id: 4,
        cost: 0,
        phone: '+7981385369',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'играем в футбол',
        date: '2022-07-18 13:00:00+03',
        description: 'Сбор 18ого в час.',
        members_count: 10,
        user_id: 2,
        sport_id: 2,
        place_id: 13,
        cost: 0,
        phone: '@vtoroy',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Events', null, {});
  },
};
